vich_uploader:
    db_driver: orm

    mappings:
        menus_images:
            uri_prefix: /images/uploads/menus
            upload_destination: '%kernel.project_dir%/public/images/uploads/menus'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      